[package]
name = "geofencing"
version = "0.1.0"
authors = ["dmoha1 <delhidurai.mohan@nike.com>"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.48"
serde_derive = "1.0.104"
serde = "1.0.104"
ansi_term = "*"